trigger:
- master

resources:
  containers:
  - container: node
    image: node:14

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'react-waiters'
  buildId: $(Build.BuildId)
  dockerRegistryServiceConnection: 'dockercontainerwaitersapp'

steps:
- task: Docker@2
  inputs:
    command: build
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):$(buildId)
    containerRegistry: $(dockerRegistryServiceConnection)
    
- task: Docker@2
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      $(imageName):$(buildId)
    containerRegistry: $(dockerRegistryServiceConnection)
