trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AzureRMServiceConnection'
  imageRepository: 'dockercontainerwaitersapp.azurecr.io/Waiters-app'
  containerRegistry: 'dockercontainerwaitersapp.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name dockercontainerwaitersapp
      docker build -t $(imageRepository):$(tag) -f $(dockerfilePath) .
      docker push $(imageRepository):$(tag)
  displayName: 'Build and push Docker image'
