trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'dockercontainerwaitersappsecond'

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

