trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'react-waiters'
  buildId: $(Build.BuildId)
  registryName: 'dockercontainerwaitersapp.azurecr.io'
  fullImageName: '$(registryName)/$(imageName):$(buildId)'

steps:
- script: echo $(fullImageName)
  displayName: 'Print Full Image Name'

- task: Docker@2
  inputs:
    command: login
    containerRegistry: 'dockercontainerwaitersapp'
    username: $(ACR_USERNAME)
    password: $(ACR_PASSWORD)

- task: Docker@2
  inputs:
    command: build
    repository: '$(imageName)'
    dockerfile: 'Dockerfile'
    tags: |
      $(fullImageName)
    containerRegistry: 'dockercontainerwaitersapp'

- task: Docker@2
  inputs:
    command: push
    repository: '$(imageName)'
    tags: |
      $(fullImageName)
    containerRegistry: 'dockercontainerwaitersapp'
