trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'react-waiters'
  buildId: $(Build.BuildId)
  fullImageName: 'dockercontainerwaitersapp.azurecr.io/$(imageName):$(buildId)'

steps:
- script: echo $(fullImageName)
  displayName: 'Print Full Image Name'

- task: Docker@2
  inputs:
    command: build
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    tags: |
      $(fullImageName)
    containerRegistry: 'dockercontainerwaitersapp'
    
- task: Docker@2
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      $(fullImageName)
    containerRegistry: 'dockercontainerwaitersapp'
