trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'react-waiters'
  buildId: $(Build.BuildId)

steps:
- task: Docker@2
  inputs:
    command: build
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):$(buildId)
    containerRegistry: 'dockercontainerwaitersapp'
    
- task: Docker@2
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      $(imageName):$(buildId)
    containerRegistry: 'dockercontainerwaitersapp'
