trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'react-waiters'
  buildId: $(Build.BuildId)
  registryName: 'dockercontainerwaitersapp.azurecr.io'
  fullImageName: 'dockercontainerwaitersapp.azurecr.io/react-waiters:Build.BuildId'

steps:
- script: echo 'dockercontainerwaitersapp.azurecr.io/react-waiters:Build.BuildId'
  displayName: 'Print Full Image Name'

- task: Docker@2
  inputs:
    command: build
    repository: 'react-waiters'
    dockerfile: '**/Dockerfile'
    tags: |
      'dockercontainerwaitersapp.azurecr.io/react-waiters:Build.BuildId'
    containerRegistry: 'dockercontainerwaitersapp'
    
- task: Docker@2
  inputs:
    command: push
    repository: 'react-waiters'
    tags: |
      'dockercontainerwaitersapp.azurecr.io/react-waiters:Build.BuildId'
    containerRegistry: 'dockercontainerwaitersapp'
